# Extract drug df
drug_df <- function(rec) {
  tibble::tibble(
    primary_key = XML::xmlValue(rec["drugbank-id"][[1]]),
    secondary_key = ifelse(length(rec["drugbank-id"]) > 1, XML::xmlValue(rec["drugbank-id"][[2]]), NA),
    third_key = ifelse(length(rec["drugbank-id"]) > 2, XML::xmlValue(rec["drugbank-id"][[3]]), NA),
    type = XML::xmlGetAttr(node = rec, name = "type"),
    created = as.Date(XML::xmlGetAttr(node = rec, name = "created")),
    updated = as.Date(XML::xmlGetAttr(node = rec, name = "updated")),
    name = XML::xmlValue(rec[["name"]]),
    description = XML::xmlValue(rec[["description"]]),
    cas_number = XML::xmlValue(rec[["cas-number"]]),
    unii = XML::xmlValue(rec[["unii"]]),
    state = XML::xmlValue(rec[["state"]]),
    groups_count = XML::xmlSize(rec[["groups"]]),
    articles_count = XML::xmlSize(rec[["general-references"]][["articles"]]),
    books_count = XML::xmlSize(rec[["general-references"]][["textbooks"]]),
    links_count = XML::xmlSize(rec[["general-references"]][["links"]]),
    synthesis_reference = XML::xmlValue(rec[["synthesis-reference"]]),
    indication = XML::xmlValue(rec[["indication"]]),
    pharmacodynamics = XML::xmlValue(rec[["pharmacodynamics"]]),
    mechanism_of_action = XML::xmlValue(rec[["mechanism-of-action"]]),
    metabolism = XML::xmlValue(rec[["metabolism"]]),
    absorption = XML::xmlValue(rec[["absorption"]]),
    half_life = XML::xmlValue(rec[["half-life"]]),
    protein_binding = XML::xmlValue(rec[["protein-binding"]]),
    route_of_elimination = XML::xmlValue(rec[["route-of-elimination"]]),
    volume_of_distribution = XML::xmlValue(rec[["volume-of-distribution"]]),
    clearance = XML::xmlValue(rec[["clearance"]]),
    synonyms_count = XML::xmlSize(rec[["synonyms"]]),
    products_count = XML::xmlSize(rec[["products"]]),
    international_brands = XML::xmlValue(rec[["international-brands"]]),
    mixtures_count = XML::xmlSize(rec[["mixtures"]]),
    manufacturers_count = XML::xmlSize(rec[["manufacturers"]]),
    prices_count = XML::xmlSize(rec[["prices"]]),
    categories_count = XML::xmlSize(rec[["categories"]]),
    affected_organisms_count = XML::xmlSize(rec[["affected-organisms"]]),
    dosages_count = XML::xmlSize(rec[["dosages"]]),
    atc_codes_count = XML::xmlSize(rec[["atc-codes"]]),
    ahfs_codes_count = XML::xmlSize(rec[["ahfs-codes"]]),
    pdb_entries = XML::xmlSize(rec[["pdb-entries"]]),
    fda_label = XML::xmlValue(rec[["fda-label"]]),
    msds = XML::xmlValue(rec[["msds"]]),
    patents_count = XML::xmlSize(rec[["patents"]]),
    food_interactions = XML::xmlSize(rec[["food-interactions"]]),
    drug_interactions_count = XML::xmlSize(rec[["drug-interactions"]]),
    sequences_count = XML::xmlSize(rec[["sequences"]]),
    experimental_properties_count = XML::xmlSize(rec[["experimental-properties"]]),
    external_identifiers_count = XML::xmlSize(rec[["external-identifiers"]]),
    external_links_count = XML::xmlSize(rec[["external-links"]]),
    pathways_count = XML::xmlSize(rec[["pathways"]]),
    reactions_count = XML::xmlSize(rec[["reactions"]]),
    snp_effects_count = XML::xmlSize(rec[["snp-effects"]]),
    snp_adverse_drug_reactions_count = XML::xmlSize(rec[["snp-adverse-drug-reactions"]]),
    targets_count = XML::xmlSize(rec[["targets"]]),
    enzymes_count = XML::xmlSize(rec[["enzymes"]]),
    carriers_count = XML::xmlSize(rec[["carriers"]]),
    transporters_count = XML::xmlSize(rec[["transporters"]]),
    toxicity = XML::xmlValue(rec[["toxicity"]])
  )
}
